### PR TITLE
Add travis-ci auto build support

### PR DESCRIPTION
**Pull request by kurumi-moe**
1. Add `travis-ci` auto build support
2. Update README

### CODE REVIEW

**Comment by clowwindy** [comment]
Thanks, merged.

By the way, I'm looking for someone who's familiar with Android and JNI to maintain this project. Would you like to work on this project with @Joosun ?

**Comment by kurumi-moe** [comment]
Yes, I'm glad to.

clowwindy <notifications@github.com>于2015年8月20日周四 00:20写道：

**Comment by clowwindy** [comment]
I've added you to the collaborators. You can start working on this project.

Thanks again!

**Comment by clowwindy** [comment]
I'm sorry but something has just happened. I have to stop this project.

**Comment by qdzheng** [comment]
@clowwindy you are great, thank you for what you done.

**Comment by wopkli** [comment]
LOCAL_SRC_FILES points to a missing file libshadowvpn.a

**Pull request merged**
