### PR TITLE
Add user_token support for ShadowVPNAndroid

### PR DESCRIPTION
**Pull request by kurumi-moe**
1. Add `user token` support for ShadowVPNAndroid
2. Update shadowvpn to 0.2.0
3. Add jni build script `make-jni.sh`

### CODE REVIEW

**Comment by clowwindy** [comment]
JNI part looks good to me.

@Joosun 
Would you like to take a look at the UI part?

**Comment by clowwindy** [comment]
Seems there's some problem with the code style and indentation, making the diff harder to review.

image

**Comment by clowwindy** [comment]
@kurumi-moe You don't have to open a new pull request. You can push new commits, it will update automatically.

**Comment by kurumi-moe** [comment]
@clowwindy 

Thanks for your notice, I didn't know it. And thanks for all of your hard work.

I will add `travis-ci` auto build script later.

**Comment by clowwindy** [comment]
@kurumi-moe Thanks in advance.

**Pull request closed without merging**
